query FetchLocalRunReport($owner: String!, $name: String!, $runId: String!) {
  repository(owner: $owner, name: $name) {
    settings {
      allowedRegression
    }
    run(id: $runId) {
      id
      status
      url
      headReports {
        id
        impact
        conclusion
      }
      results {
        benchmark {
          name
          executor
        }
        value
        valgrind {
          timeDistribution {
            ir
            l1m
            llm
            sys
          }
        }
        walltime {
          iterations
          stdev
          totalTime
        }
        memory {
          peakMemory
          totalAllocated
          allocCalls
        }
      }
    }
  }
}
