name: CI
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  pull-requests: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: moonrepo/setup-rust@v1
        with:
          components: rustfmt, clippy
      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: moonrepo/setup-rust@v1
      - run: cargo test --all

  check-todos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check for todos
        id: check-todos
        run: ./scripts/show-todos.sh
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@24bffb9b452ba05a4f3f77933840a6a841d1b32b
        with:
          message: |
            ${{ steps.check-todos.outputs.pr-comment }}
          comment-tag: execution
          mode: ${{ steps.check-todos.outputs.pr-comment == '' && 'delete' || 'upsert' }}
