name: CI
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: moonrepo/setup-rust@v1
        with:
          components: rustfmt, clippy
      - run: sudo apt-get update && sudo apt-get install -y libelf-dev protobuf-compiler
      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - uses: moonrepo/setup-rust@v1
      - run: sudo apt-get update && sudo apt-get install -y libelf-dev protobuf-compiler
      - run: cargo test --all --exclude heaptrack

  bpf-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - uses: moonrepo/setup-rust@v1
      - uses: extractions/setup-just@v3
      - run: sudo apt-get update && sudo apt-get install -y libelf-dev protobuf-compiler
      - run: cd crates/heaptrack && just test
